Fixed a typo (logging.log) and use "repr(coords)" to make coords into a string
My pwny was not saving .gps.json files, even though I had gps lock. I saw an error in the logs on line 318:

  File "/usr/local/share/pwnagotchi/custom-plugins/gpsdeasy.py", line 318, in on_handshake
    logging.log("!!!!! " + coords)
                ~~~~~~~~~^~~~~~~~
TypeError: can only concatenate str (not "dict") to str

Then it didn't like logging.log, so I switched to .debug. there apparently is a logging.log, but it takes different arguments (that I do not know)